### ISSUE TITLE
Suggested change in vignette

### ISSUE THREAD

**Issue by marynias** [mikelove/mrlocus#2]
Hi,
I am following the vignette and I got to this part:
**The second function takes the output of the first function, and additionally a number of column names. E.g. this function call implies that we have column names eqtl_ref, eqtl_effect, eqtl_beta, eqtl_se, etc. See the function man page for more details.

 (un-evaluated chunk)
data2 <- flipAllelesAndGather(data1$sum_stat, data1$ld_mat,
                              a="eqtl", b="gwas",
                              ref="ref", eff="effect",
                              beta="beta", se="se",
                              a2_plink="major_plink",
                              snp_id="SNP", sep="_")
I suggest that you also specify the parameter  `ab_last = FALSE` ** in that case, as the example in the text (eqtl_ref etc.) will not work without it. It took me a while to figure this out, so posting it here in case it saves someone else's time.

**Comment by mikelove** [comment]
hi @marynias Thanks for posting the issue, and sorry for the confusion. I've corrected the documentation now.
