### ISSUE TITLE
Using lbf_variable from SuSiE in MRLocus

### ISSUE THREAD

**Issue by kauralasoo** [mikelove/mrlocus#7]
Hi Mike,

Do you think it would be possible/interesting to modify MRLocus to use log Bayes factors (lbf's) computed by SuSiE for the colocalisation part? For the next eQTL Catalogue release we are planning to release lbfs from SuSiE fine mapping alongside with our standard summary statistics to support the new coloc.susie method from Chris Wallace. Internally, we have also just started to play around with standard IVW MR applied to pairwise colocalising signals from coloc.susie with promising results. 

From the eQTL Catalogue perspective, it is much easier for us to share the lbfs from each fine-mapped locus rather than the large in-sample LD matrices from all studies.

Best,
Kaur

**Comment by mikelove** [comment]
Yes absolutely. We often use eCAVIAR CLPP, but could use LBF instead. Would you have 15 min to chat this week about potential use cases?

**Comment by kauralasoo** [comment]
For others who are curious, we ended up taking the colocalising variant pairs directly from coloc.susie and then fit the MRLocus model with fitSlope() function.
